command:
  - /bin/bash
  - start.sh

env:
  - name: MOCK_MODE
    value: "true"
  - name: DEBUG
    value: "true"
  - name: CATALOG_NAME
    value: "marcin_demo2"
  - name: SCHEMA_NAME
    value: "hedis_measurements"
  - name: AGENT_ENDPOINT
    value: "hedis_chat_agent"
  - name: ENABLE_AUTH
    value: "false"
  - name: ALLOWED_USERS
    value: ""
  - name: EFFECTIVE_YEAR
    value: "2025"
