command:
  - /bin/sh
  - -c
  - uvicorn main:app --host 0.0.0.0 --port $DATABRICKS_APP_PORT

env:
  - name: MOCK_MODE
    value: "true"
  - name: DEBUG
    value: "true"
  - name: CATALOG_NAME
    value: "marcin_demo2"
  - name: SCHEMA_NAME
    value: "hedis_measurements"
  - name: AGENT_ENDPOINT
    value: "hedis_chat_agent"
  - name: ENABLE_AUTH
    value: "false"
  - name: ALLOWED_USERS
    value: ""
  - name: APP_NAME
    value: "HEDIS Chat API"
  - name: APP_VERSION
    value: "1.0.0"
  - name: EFFECTIVE_YEAR
    value: "2025"
  - name: HOST
    value: "0.0.0.0"
  - name: CORS_ORIGINS
    value: '["*"]'
  - name: CORS_CREDENTIALS
    value: "true"
  - name: CORS_METHODS
    value: '["*"]'
  - name: CORS_HEADERS
    value: '["*"]'
  - name: POSTGRES_ENABLED
    value: "false"
