"""HEDIS Agent Prompts Module"""

from .hedis import (
    MEASURE_EXTRACTION_PROMPT,
    METADATA_EXTRACTION_PROMPT,
    MEASURE_EXTRACTION_SCHEMA,
    METADATA_EXTRACTION_SCHEMA,
    HEDIS_CHAT_AGENT_SYSTEM_PROMPT,
    HEDIS_QNA_MODE_PROMPT,
    HEDIS_COMPLIANCE_MODE_PROMPT,
    HEDIS_INTENT_DETECTION_PROMPT,
    HEDIS_PATIENT_DATA_EXTRACTION_PROMPT,
    HEDIS_INTENT_DETECTION_SCHEMA,
    HEDIS_PATIENT_DATA_EXTRACTION_SCHEMA,
)

__all__ = [
    "MEASURE_EXTRACTION_PROMPT",
    "METADATA_EXTRACTION_PROMPT",
    "MEASURE_EXTRACTION_SCHEMA",
    "METADATA_EXTRACTION_SCHEMA",
    "HEDIS_CHAT_AGENT_SYSTEM_PROMPT",
    "HEDIS_QNA_MODE_PROMPT",
    "HEDIS_COMPLIANCE_MODE_PROMPT",
    "HEDIS_INTENT_DETECTION_PROMPT",
    "HEDIS_PATIENT_DATA_EXTRACTION_PROMPT",
    "HEDIS_INTENT_DETECTION_SCHEMA",
    "HEDIS_PATIENT_DATA_EXTRACTION_SCHEMA",
]
